import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderComponent from "@/components/header";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir={"rtl"} className={'text-2xl'}>
      <body>
      <HeaderComponent/>
      {children}
      </body>
    </html>
  )
}
